const representativeData = [
  {
    id: '1',
    firstName: 'Tim',
    lastName: 'Ackert',
    district: '008',
    yearElected: '2011',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710170522/Representative%20Photos/TimAckert_xno4jt.jpg',
    party: 'Republican',
    gunSenseCandidate: 'false',
    supportHB6667: 'false',
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_8.pdf',
  },
  {
    id: '2',
    firstName: 'Raghib',
    lastName: 'Allie-Brennan',
    district: '002',
    yearElected: '2018',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710173150/Representative%20Photos/RaghibAllie-Brennan_nktqsw.jpg',
    party: 'Democrat',
    gunSenseCandidate: 'true',
    supportHB6667: 'true',
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_2.pdf',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },

  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
];

export default representativeData;
