const representativeData = [
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },

  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
];

export default representativeData;
