const representativeData = [
  {
    id: '1',
    firstName: 'Tim',
    lastName: 'Ackert',
    district: '008',
    yearElected: '2011',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710170522/Representative%20Photos/TimAckert_xno4jt.jpg',
    party: 'Republican',
    gunSenseCandidate: false,
    supportHB6667: false,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_8.pdf',
  },
  {
    id: '2',
    firstName: 'Raghib',
    lastName: 'Allie-Brennan',
    district: '002',
    yearElected: '2018',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710173150/Representative%20Photos/RaghibAllie-Brennan_nktqsw.jpg',
    party: 'Democrat',
    gunSenseCandidate: true,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_2.pdf',
  },
  {
    id: '3',
    firstName: 'Mark',
    lastName: 'Anderson',
    district: '062',
    yearElected: '2021',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710173675/Representative%20Photos/MarkAnderson_l5zzjr.jpg',
    party: 'Republican',
    gunSenseCandidate: false,
    supportHB6667: false,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_62.pdf',
  },
  {
    id: '4',
    firstName: 'Chris',
    lastName: 'Aniskovich',
    district: '035',
    yearElected: '2019',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710174081/Representative%20Photos/ChrisAniskovich_qweiry.png',
    party: 'Republican',
    gunSenseCandidate: false,
    supportHB6667: false,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_35.pdf',
  },
  {
    id: '5',
    firstName: 'Tom',
    lastName: 'Arnone',
    district: '058',
    yearElected: '2019',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710174277/Representative%20Photos/TomArnone_zmikwk.png',
    party: 'Democrat',
    gunSenseCandidate: false,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_58.pdf',
  },
  {
    id: '6',
    firstName: 'Hector',
    lastName: 'Arzeno',
    district: '151',
    yearElected: '2023',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710174573/Representative%20Photos/HectorArzeno_k57gym.png',
    party: 'Democrat',
    gunSenseCandidate: true,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_151.pdf',
  },
  {
    id: '7',
    firstName: 'Andre',
    lastName: 'Baker',
    district: '124',
    yearElected: '2015',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710174761/Representative%20Photos/AndreBaker_k2dfuw.jpg',
    party: 'Democrat',
    gunSenseCandidate: false,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_124.pdf',
  },
  {
    id: '8',
    firstName: 'Jill',
    lastName: 'Barry',
    district: '031',
    yearElected: '2019',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710175053/Representative%20Photos/jillBarry_welqee.jpg',
    party: 'Democrat',
    gunSenseCandidate: false,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_31.pdf',
  },
  {
    id: '9',
    firstName: 'Kai',
    lastName: 'Belton',
    district: '100',
    yearElected: '2023',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710175225/Representative%20Photos/KaiBelton_gar32l.jpg',
    party: 'Democrat',
    gunSenseCandidate: false,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_100.pdf',
  },
  {
    id: '10',
    firstName: 'Aimee',
    lastName: 'Berger-Girvalo',
    district: '111',
    yearElected: '2020',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1710175374/Representative%20Photos/AimeeBerger-Girvalo_kegnls.jpg',
    party: 'Democrat',
    gunSenseCandidate: true,
    supportHB6667: true,
    repDistrict:
      'https://www.cga.ct.gov/rr/tfs/20210401_2021%20Redistricting%20Project/NODISPLAY_data/housemaps/Individual%20District%20Maps/House%20Districts_111.pdf',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },

  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
  {
    id: '',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: '',
    supportHB6667: '',
    repDistrict: '',
  },
];

export default representativeData;
