const senatorData = [
  {
    id: '1',
    firstName: 'Saud',
    lastName: 'Anwar',
    district: 'S03',
    yearElected: 2020,
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707058079/Senator%20Photos/saudAnwar_wffasu.png',
    party: 'Democrat',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707071583/Senate%20Districts/senateDistrictThree_pfz7dv.png',
  },
  {
    id: '2',
    firstName: 'Eric',
    lastName: 'Berthel',
    district: 'S32',
    yearElected: '2017',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707058079/Senator%20Photos/ericBerthel_jvvygm.jpg',
    party: 'Republican',
    gunSenseCandidate: false,
    supportHB6667: false,
    senateDistrict: '',
  },
  {
    id: '3',
    firstName: 'Jorge',
    lastName: 'Cabrera',
    district: 'S17',
    yearElected: '2021',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707058079/Senator%20Photos/jorgeCabrera_lmj4dd.jpg',
    party: 'Democrat',
    gunSenseCandidate: false,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '4',
    firstName: 'Paul',
    lastName: 'Cicarella',
    district: 'S34',
    yearElected: 2020,
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707070385/Senator%20Photos/paulCicarella_vdrjya.jpg',
    party: 'Republican',
    gunSenseCandidate: false,
    supportHB6667: false,
    senateDistrict: '',
  },
  {
    id: '5',
    firstName: 'Christine',
    lastName: 'Cohen',
    district: 'S12',
    yearElected: '2019',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707070567/Senator%20Photos/christineCohen_xeitsd.jpg',
    party: 'Democrat',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '6',
    firstName: 'Bob',
    lastName: 'Duff',
    district: 'S25',
    yearElected: '2001',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707072590/Senator%20Photos/bobDuff_wkel3l.jpg',
    party: 'Democrat',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '7',
    firstName: 'Ryan',
    lastName: 'Fazio',
    district: 'S36',
    yearElected: '2021',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707073326/Senator%20Photos/ryanFazio_r4y8ek.jpg',
    party: 'Republican',
    gunSenseCandidate: false,
    supportHB6667: false,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: 'Mae',
    lastName: 'Flexer',
    district: 'S29',
    yearElected: '2008',
    photoURL:
      'https://res.cloudinary.com/ddbc9j5u9/image/upload/v1707073527/Senator%20Photos/maeFlexer_mp3nhx.jpg',
    party: 'Democrat',
    gunSenseCandidate: false,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
  {
    id: '8',
    firstName: '',
    lastName: '',
    district: '',
    yearElected: '',
    photoURL: '',
    party: '',
    gunSenseCandidate: true,
    supportHB6667: true,
    senateDistrict: '',
  },
];

export default senatorData;
